server:
  port: 6661   #设置端口号

#默认设置下，服务注册中心也会将自己作为客户端来尝试注册自己，所以需要禁用它的客户注册欣慰，将其设置为false
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #表示是否将自己注册到Eureka Server，默认为true
    fetch-registry: false         #表示是否从Eureka Server 中 获取注册信息。默认为true
    service-url:
      default-Zone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与Eureka Server交互地址，查询服务和注册服务都需要依赖这个地址，如果有多个地址可以使用,分割。
      